package designPrinciples.CompositionOverInheritance.TransportExample.Before;

public class AutopilotCombustionEngineTruck extends CombustionEngineTruck {
	private String dieselSavingRouteGenerationAlgorithmActivated;
}
