package designPrinciples.CompositionOverInheritance.TransportExample.Before;

public class AutopilotCombustionEngineCar extends CombustionEngineCar {
	private String fuelSavingRouteGenerationAlgorithmActivated;
}
